# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 2.5
  allowed_goal_duration_margin: 1.0
  allowed_start_tolerance: 0.01
  execution_duration_monitoring: true

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - Rotation
      - Pitch
      - Elbow
      - Wrist_Pitch
      - Wrist_Roll
    action_ns: follow_joint_trajectory
    default: true

  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - Jaw
    action_ns: follow_joint_trajectory
    default: true
